project:
  type: book
  output-dir: ./docs

bookdown::gitbook:
   
book:
  title: "Lab Book"
  author: "Bradley Day"
  date: "2025/05/19"
  downloads:
    - pdf
  chapters:
    - index.qmd
    - part: Summer Reading
      chapters:
        - Background.qmd
    - part: Teaching Block 1
      chapters:
        - Week1.qmd
        - Week2.qmd
        - Week3.qmd
        - Week4.qmd
        - Week5.qmd
        - Week6.qmd
        - Week7.qmd
        - Week8.qmd
        - Week9.qmd
        - Week10.qmd
        - Week11.qmd
        - Week12.qmd
    - part: Teaching Block 2
      chapters:
        - Week13.qmd
        - Week14.qmd
        - Week15.qmd
        - Week16.qmd
        - Week17.qmd
        - Week18.qmd
        - Week19.qmd
        - Week20.qmd
        - Week21.qmd
        - Week22.qmd
    - references.qmd

bibliography: references.bib
csl: american-physical-society-et-al.csl
lightbox: true

format:
  html:
    code-fold: true
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            loader: {
              load: ['[tex]/boldsymbol', '[tex]/physics']
            },
            tex: {
              packages: {
                '[+]': ['boldsymbol', 'physics']
              }
            }
          };
          </script>
  pdf:
    include-in-header:
      - text: |
          \usepackage{amsmath, gensymb, physics}
          \usepackage[margin=15mm]{geometry}

jupyter: python3

theme:
    light: flatly
    dark: darkly
