# Week 2

## 2026/09/29

### First Investigations Into Data Reduction

- Can now use solva, and XMM-SAS is installed.
- Have got a script to automate the reduction thanks to Darius Michienzi
    - [GitHub](https://github.com/astro-group-bristol/reduction-scripts)
    - This script is written in Julia so requires a Julia installation on solva
    - Currently running the command `julia` yields the error
        ```
        -bash: julia: command not found
        ```
    - Need to check with Rhys Morris whether Julia is installed, if so how can we access it, and if not whether we can install it
    - For now will proceed with manual reduction to learn the process, as the script may not cover all of our needs, so worth learning how it works under the hood
- Using the XMM-SAS ABC guide
    - Using dataset with OBSID 0761670101
    - Following instructions for EPIC (IMAGING Mode)
    - The first set of commands are
        ```
        cd ODF 
        setenv SAS_ODF /full/path/to/ODF/directory/
        setenv SAS_ODFPATH /full/path/to/ODF/directory/
        cifbuild
        ```
    - This does not currently work, the `setenv` command seems to be for a `csh` shell, while solva uses `bash`
        - This can be worked around by using e.g.
            ```
            export SAS_ODF="/full/path/to/ODF/directory/"
            ```
    - The `cifbuild` command also does not currently work, with the terminal giving the error that the command was not found

### Meeting with Supervisor

- Questions
    - In Fabian et al. (2002) @fabian_long_2002 it says that the red wing of the line extending below 4 keV can be explained by the disc extending within 6 $r_g$ 
        - Why is this?
        - Is this just what their fit says?
    - Maybe start considering how we are going to fit the data? 
        - It may be possible to get a headstart setting up pipelines for it
        - Discuss with Supervisor/Jacob if its worth using Julia (`SpectralFitting.jl`) or `xspec`?
            - Or something else?
        - If using Julia, would it be worth designing our model?
            - Is there anything we can gain from this? More freedom in the parameters etc?

### Meeting Minutes

- When fitting, will use XSPEC
    - Can create a table model if we need to use more abstract metrics etc.
    - Group working on catalogue of metrics have managed to get Gradus working for naked singularities (superspinning black holes)
        - May be able to use this to fit non-standard descriptions to the data, and collaboratively investigate the cosmic censorship conjecture
- Downloading data from XMM-Newton Archive
    - Through legacy interface, create download script (gives `wget` script)
    - May be able to enter RA/DEC to find OBSIDs
- Meeting was successful with Andy's other group
    - They are working on cataloguing spacetimes and investigating the cosmic censorshsolvaip conjecture
        - This is the conjecture that naked singularities do not exist
        - They may be able to compute iron line profiles with this, allowing us to fit this supposedly unphysical model to observations
        - If doing this we will need to construct a table model for XSPEC
    - Groupchat set up with Fionn & Max which should allow us to compare notes and collaborate on issues

### Misc Notes

- Recurring meeting set for 11:00 on Fridays with Jacob to keep each other in the loop and discuss issues

## 2026/09/30

### Intro to Linux Meeting (w/Rhys Morris)

- [star.bris.ac.uk/project_access](https://www.star.bris.ac.uk/project_access/)

## 2026/10/01

### XMM-SAS and Julia Setup

Once logged into solva, XMM-SAS and Julia can be set up by running:

```{.bash  .code-overflow-wrap}
module load julia/1.9.2
```

for Julia, which can be tested by simply running `julia`. XMM-SAS requires a few more lines of setup:

```{.bash  .code-overflow-wrap}
# First initialise HEASOFT

export HEADAS=/opt/local/rocky8/heasoft-6.36/x86_64-pc-linux-gnu-libc2.28/
alias heainit=". $HEADAS/headas-init.sh"
heainit

# Then initialise XMM-SAS
module load anaconda/3-2024
export SAS_DIR=/opt/local/rocky8/xmmsas_20230412_1735
source $SAS_DIR/sas-setup.sh
```

Running `sasversion` should output

```
sasversion:- Executing (routine): sasversion  -w 1 -V 4
sasversion:- sasversion (sasversion-1.3)  [xmmsas_20230412_1735-21.0.0] started:  2026-10-01T10:13:30.000
sasversion:- XMM-Newton SAS release and build information:

SAS release: xmmsas_20230412_1735-21.0.0
Compiled on: Sun Apr 16 21:03:42 CEST 2023
Compiled by: sasbuild@sasbld05.iuser.lan
Platform   : RHEL8.6

SAS-related environment variables that are set:

SAS_DIR = /opt/local/rocky8/xmmsas_20230412_1735
SAS_PATH = /opt/local/rocky8/xmmsas_20230412_1735

sasversion:- sasversion (sasversion-1.3)  [xmmsas_20230412_1735-21.0.0] ended:    2026-10-01T10:13:30.000
```
